config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :kudos
  devise_for :employees
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # add root route
  root to: "kudos#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/kudo.rb
class Kudo < ApplicationRecord
  belongs_to :giver, class_name: 'Employee'
  belongs_to :receiver, class_name: 'Employee'

  validates :title, :content, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_employee!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/kudos_controller.rb
class KudosController < ApplicationController
  before_action :set_kudo, only: %i[show edit update destroy]

  # GET /kudos
  def index
    @kudos = Kudo.all
  end

  # GET /kudos/1
  def show; end

  # GET /kudos/new
  def new
    @kudo = Kudo.new
  end

  # GET /kudos/1/edit
  def edit; end

  # POST /kudos
  def create
    @kudo = Kudo.new(kudo_params)
    @kudo.giver = current_employee

    if @kudo.save
      redirect_to kudos_path, notice: 'Kudo was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /kudos/1
  def update
    if @kudo.update(kudo_params)
      redirect_to @kudo, notice: 'Kudo was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /kudos/1
  def destroy
    @kudo.destroy
    redirect_to kudos_url, notice: 'Kudo was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_kudo
    @kudo = Kudo.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def kudo_params
    params.require(:kudo).permit(:title, :content, :giver_id, :receiver_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #791bab;">
  <div class="container-fluid">
    <%= link_to 'Employee Recognition Platform', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
      data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if employee_signed_in? %>
          <%= link_to "Sign out", destroy_employee_session_path, method: :delete, class:"nav-link" %>
        <% else %>
          <%= link_to "Sign up", new_employee_registration_path, class:"nav-link" %>
          <%= link_to "Sign in", new_employee_session_path, class:"nav-link" %>
        <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div>Hey, It works</div>

app/views/kudos/_form.html.erb
<%= form_with(model: kudo) do |form| %>
<% if kudo.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(kudo.errors.count, "error") %> prohibited this kudo from being saved:</h2>

  <ul>
    <% kudo.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div style="margin: auto">
  <div class="card" style="width: 48rem; margin: auto">
    <div class="card-header text-white bg-dark">
      Add a kudo!
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item bg-light">
        <div class="input title">
          <label class="form-label"><%= form.label :title %></label>
          <%= form.text_field :title, type:"text", class:"form-control", placeholder:"Enter your title", :required => true %>
        </div>
      </li>
      <li class="list-group-item bg-light">
        <div class="input content">
          <label class="form-label"><%= form.label :content %></label>
          <%= form.text_area :content, class:"form-control", rows:"3", placeholder:"Enter your kudo content", :required => true %>
        </div>
      </li>
      <li class="list-group-item bg-light">
        <div>
          <label class="form-label"><%= form.label :receiver_id %></label>
          <%= form.collection_select(:receiver_id, Employee.where.not(id: current_employee), :id, :email, {}, {class:"form-select"}) %>
        </div>
      </li>
    </ul>
  </div>
  <br>
  <div class="d-grid gap-2 col-6 mx-auto">
    <%= form.submit class:'btn btn-dark' %>
  </div>
  <% end %>
</div>

app/views/kudos/edit.html.erb
<h1>Editing Kudo</h1>

<%= render 'form', kudo: @kudo %>

<hr/>
<div class="d-grid gap-2 col-6 mx-auto">
  <%= link_to 'Show', @kudo, class:"btn btn-primary" %>
  <%= link_to 'Back', kudos_path, class:"btn btn-secondary" %>
</div>

app/views/kudos/index.html.erb
<h1>Kudos</h1>

<table class="table table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Giver</th>
      <th>Receiver</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% @kudos.each do |kudo| %>
    <% if kudo.giver.email == current_employee.email %>
      <tr>
        <td><%= kudo.title %></td>
        <td><%= kudo.content %></td>
        <td><%= kudo.giver.email %></td>
        <td><%= kudo.receiver.email %></td>
        <td><%= link_to 'Show', kudo, class:"btn btn-outline-primary btn-sm" %></td>
        <td><%= link_to 'Edit', edit_kudo_path(kudo), class:"btn btn-outline-secondary btn-sm" %></td>
        <td><%= link_to 'Destroy', kudo, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
<hr/>
<div class="d-grid gap-2 col-6 mx-auto">
  <%= link_to 'New Kudo', new_kudo_path, class:"btn btn-dark" %>
</div>

app/views/kudos/new.html.erb
<h1>New Kudo</h1>

<%= render 'form', kudo: @kudo %>
<hr/>
<div class="d-grid gap-2 col-6 mx-auto">
  <%= link_to 'Back', kudos_path, class:"btn btn-secondary" %>
</div>

app/views/kudos/show.html.erb
<h1>View Kudo</h1>

<table class="table table-striped ">
  <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Giver</th>
      <th>Receiver</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= @kudo.title %></td>
        <td><%= @kudo.content %></td>
        <td><%= @kudo.giver.email %></td>
        <td><%= @kudo.receiver.email %></td>
      </tr>
  </tbody>
</table>

<br>
<hr/>
<div class="d-grid gap-2 col-6 mx-auto">
  <%= link_to 'Edit', edit_kudo_path(@kudo), class:"btn btn-dark" %>
  <%= link_to 'Back', kudos_path, class:"btn btn-secondary" %>
</div>

app/views/layouts/_alerts.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>

<br />
<% if notice %>
<div class="alert alert-primary d-flex align-items-center" role="alert">
  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Info:"><use xlink:href="#info-fill"/></svg>
  <div>
    <%= notice %>
  </div>
</div>
<% end %>

<% if alert %>
<div class="alert alert-danger d-flex align-items-center" role="alert">
  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:">
    <use xlink:href="#exclamation-triangle-fill" />
  </svg>
  <div>
    <%= alert %>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous">

    <!-- title -->
    <title>Employee Recognition Platform</title>

    <!-- inherited  -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <!-- header partial -->
    <%= render 'home/header' %>
    <!-- alerts section - required by devise and other -->
    <div>
      <br>
      <% if notice || alert %>
      <%= render 'layouts/alerts' %>
      <% end %>
    </div>
    <!-- main payload -->
    <div class="container" style="margin: auto">
      <%= yield %>
    </div>
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"></script>
  </body>

</html>